# fly.toml app configuration file for shot-counter
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shot-counter"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    BUILD_COMMAND = "bin/rails fly:build"
    SERVER_COMMAND = "bin/rails fly:server"

[deploy]
  # release_command = "bin/rails fly:release"

[env]
  PORT = "8080"
  # REDIS_URL is not needed here if set in Fly.io secrets

[processes]
  app = "bin/rails fly:server"
  worker = "bundle exec sidekiq"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
  
  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
