version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  test:
    docker:
      # Primary container image
      - image: cimg/ruby:3.2.2
        environment:
          RAILS_ENV: test
          RAILS_MASTER_KEY: 2cffd5a092c61292b6885e61e8a4a12f
          POSTGRES_HOST: 127.0.0.1
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: shot_server_test
      
      # PostgreSQL database
      - image: cimg/postgres:15.0
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: shot_server_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
      
      # Redis
      - image: cimg/redis:7.0
    
    working_directory: ~/repo
    
    steps:
      - checkout
      
      # Install system dependencies
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libpq-dev postgresql-client libvips-dev
      
      # Cache Ruby gems
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      
      # Install Ruby dependencies
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      
      # Save cache
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      
      # Wait for database
      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      
      # Database setup
      - run:
          name: Database setup
          command: |
            RAILS_ENV=test bundle exec rails db:create
            RAILS_ENV=test bundle exec rails db:schema:load
      
      # Run RSpec tests
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress
      
      # Store test results for CircleCI
      - store_test_results:
          path: /tmp/test-results
      
      # Store test artifacts
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  version: 2
  test:
    jobs:
      - test