version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          RAILS_ENV: test
          DATABASE_URL: postgresql://circleci@127.0.0.1:5432/shot_server_test
          DISABLE_SPRING: 1
          DISABLE_BOOTSNAP: 1
      
      - image: cimg/postgres:15.0
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: shot_server_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
    
    steps:
      - checkout
      
      # Simple dependency installation
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libpq-dev postgresql-client
            
            gem install bundler -v 2.4.10
            bundle _2.4.10_ config set --local path 'vendor/bundle'
            bundle _2.4.10_ install --jobs=4 --retry=3
      
      # Wait for database
      - run:
          name: Wait for DB
          command: |
            for i in {1..10}; do
              pg_isready -h localhost -U circleci && break
              echo "Waiting for database..."
              sleep 2
            done
      
      # Database setup
      - run:
          name: Database setup
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
      
      # Simple test run with explicit timeout
      - run:
          name: Run tests
          command: |
            # Run a simple test to verify setup
            timeout 30 bundle exec rspec spec/models/user_spec.rb --format progress || true
            
            # If that worked, run all tests with timeout
            timeout 180 bundle exec rspec --format progress --fail-fast || exit 1
          no_output_timeout: 4m

workflows:
  version: 2
  test:
    jobs:
      - test